[package]
name = "weird-algorithm"
version = "0.1.0"
authors = ["Martin Beentjes <martin@beentjes.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
